query getAllProducts {
  getAllProducts {
    id
    title
    description
    price
    img
  }
}

query getProductById($getProductByIdId: ID!) {
  getProductById(id: $getProductByIdId) {
    id
    title
    description
    price
    img
  }
}